name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Fix Linter Issues (if any)
        run: npm run lint:fix

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Use the secret token
        run: |
          echo "Checking if GH_PAT is set..."
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "❌ GH_PAT is EMPTY. Check your repository secrets!"
            exit 1
          else
            echo "✅ GH_PAT is SET."
          fi
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git commit -m "Automated README update" || echo "No changes to commit"
          git push origin main

  deploy:
    needs: ci  # This ensures deployment only happens if CI passes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Store this in GitHub secrets
          HEROKU_APP_NAME: "your-heroku-app-name"
        run: |
          echo "Deploying to Heroku..."
          heroku git:remote -a $HEROKU_APP_NAME
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
